Repository 2024-Summer-Bootcamp-Team-N/Frontend, pull requests merged in 2024-07, with the labels that each got.

#3 [chore] 초기 세팅
  .eslintrc.cjs
  .gitignore
  .prettierrc
  Dockerfile
  README.md
  index.html
  package.json
  postcss.config.cjs
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 환경설정

#5 [chore] 개발초기세팅이용~
  .yarnrc.yml
  package.json
Labels: 환경설정

#9 [design] 메인페이지 퍼블리싱
  index.html
  package.json
  src/App.css
  src/App.tsx
  src/assets/img/LogoWhite.svg
  src/assets/img/Main.svg
  src/assets/img/Main1.svg
  src/assets/img/Main2.svg
  src/assets/img/Main3.svg
  src/assets/img/SearchBtnBottom.svg
  src/assets/img/SearchBtnTop.svg
  src/assets/react.svg
  src/fonts/NanumSquare/NanumSquareB.ttf
  src/fonts/NanumSquare/NanumSquareEB.ttf
  src/fonts/NanumSquare/NanumSquareL.ttf
  src/fonts/NanumSquare/NanumSquareR.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundB.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundEB.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundL.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundR.ttf
  src/index.css
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  tailwind.config.js
  yarn.lock
Labels: 퍼블리싱

#13 design: 상단바 컴포넌트
  package-lock.json
  package.json
  src/assets/img/LogoBlue.svg
  src/components/Navbar.tsx
  src/fonts/NanumSquare/NanumSquareB.ttf
  src/fonts/NanumSquare/NanumSquareEB.ttf
  src/fonts/NanumSquare/NanumSquareL.ttf
  src/fonts/NanumSquare/NanumSquareR.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundB.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundEB.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundL.ttf
  src/fonts/NanumSquareRound/NanumSquareRoundR.ttf
  src/images.d.ts
  src/index.css
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MapPage.tsx
  src/pages/SignupPage.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  yarn.lock
Labels: 퍼블리싱

#16 [fix] 상단바 퍼블리싱 수정
  package-lock.json
  package.json
  src/components/Navbar.tsx
  yarn.lock
Labels: 오류수정

#21 [design] 로그인,회원가입 페이지 수정
  src/App.tsx
  src/assets/img/Main.svg
  src/components/Login.tsx
  src/components/Signup.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
Labels: 퍼블리싱

#20 [design] 부동산 임대차 계약서 구현
  src/assets/img/PaperIcon.svg
  src/components/ContractPaper.tsx
  src/components/Navbar.tsx
Labels: 퍼블리싱

#24 [feat] 지도페이지 사이드바 구현
  src/App.tsx
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
  src/pages/ConsultingPage.tsx
  src/pages/MapPage.tsx
Labels: 퍼블리싱

#26 [Design] 상담화면 페이지 퍼블리싱
  src/assets/img/Avatar.svg
  src/components/Navbar.tsx
  src/pages/ConsultingPage.tsx
  yarn.lock
Labels: 퍼블리싱

#28 [design] 사이드바1,2 수정
  src/assets/img/Graph1.svg
  src/assets/img/Graph2.svg
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
  src/pages/MainPage.tsx
  src/pages/MapPage.tsx
Labels: 퍼블리싱

#29 [design] 부동산 임대차 계약서 구현
  src/App.tsx
  src/assets/img/navigate_before.svg
  src/assets/img/navigate_next.svg
  src/components/ContractPaper.tsx
  src/pages/SignupPage.tsx
Labels: 퍼블리싱

#34 [design] 계약서 보관함 퍼블리싱
  src/App.tsx
  src/pages/StoragePage.tsx
Labels: 퍼블리싱

#35 [feat/#10] 지도 페이지 구현
  src/App.tsx
  src/assets/img/ActiveOption.svg
  src/assets/img/InactiveOption.svg
  src/assets/img/MapIcon.svg
  src/assets/img/MapMinus.svg
  src/assets/img/MapPlus.svg
  src/assets/img/RegionOption.svg
  src/assets/img/Search.svg
  src/assets/img/SellingOption.svg
  src/assets/img/SellingOption2.svg
  src/components/Map.tsx
  src/components/Navbar2.tsx
  src/components/ParkingNumberModal.tsx
  src/components/RegionModal.tsx
  src/components/RoomNumberModal.tsx
  src/components/SellingTypeModal.tsx
  src/index.css
  src/pages/AptPage.tsx
  src/pages/HousePage.tsx
  src/pages/MapPage.tsx
  src/pages/OfficePage.tsx
  src/pages/RoomPage.tsx
  src/vite-env.d.ts
Labels: 기능구현, 퍼블리싱

#36 [feat/#33] 회원가입 api연동 완료
  news-tutorial/package.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/Signup.tsx
  yarn.lock
Labels: 기능구현

#37 [feat/#31]로그인&로그아웃 API 연동
  src/App.tsx
  src/components/Login.tsx
  src/components/Navbar.tsx
  src/components/Navbar2.tsx
Labels: 기능구현

#42 [design]주택빌라페이지 구현
  src/pages/AptPage.tsx
  src/pages/HousePage.tsx
Labels: 퍼블리싱

#44 [design] 맵페이지 오피스텔 구현
  src/pages/OfficePage.tsx
Labels: 퍼블리싱

#43 [design] 원룸투룸페이지 퍼블리싱
  src/assets/img/ActiveOption2.svg
  src/assets/img/InactiveOption2.svg
  src/assets/img/NavigateBefore.svg
  src/assets/img/NavigateNext.svg
  src/assets/img/SearchBtn.svg
  src/components/RegionModal.tsx
  src/components/RoomNumberModal.tsx
  src/pages/AptPage.tsx
  src/pages/RoomPage.tsx
  src/pages/StoragePage.tsx
Labels: 퍼블리싱

#40 [design] 계약서 페이지 추가
  src/App.tsx
  src/assets/img/DeleteIcon.svg
  src/assets/img/DownloadIcon.svg
  src/assets/img/Inside.svg
  src/assets/img/Questions.svg
  src/assets/img/ShareIcon.svg
  src/components/Sidebar2.tsx
  src/pages/ConsultingPage.tsx
  src/pages/ContractPage.tsx
Labels: 퍼블리싱

#46 [refactor] 전체적인 퍼블리싱 수정
  src/App.tsx
  src/assets/img/HouseImage.png
  src/assets/img/MapMarker.svg
  src/assets/img/SearchBtn.svg
  src/components/MapMarker.tsx
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/pages/HousePage.tsx
  src/pages/MainPage.tsx
  src/pages/OfficePage.tsx
Labels: 리팩토링

#49 [design] 계약서 보관함 일부 수정
  src/pages/StoragePage.tsx
Labels: 퍼블리싱

#53 [refactor] 로그인 후 경로 수정
  docker-compose.yml
  src/components/Login.tsx
  src/components/Navbar.tsx
  src/components/Signup.tsx
  src/pages/OfficePage.tsx
Labels: 리팩토링

#54 [design] 사용자 입력 받는 페이지 퍼블리싱
  src/App.tsx
  src/components/Input.tsx
  src/components/Input2.tsx
  src/pages/InputPage.tsx
Labels: 퍼블리싱

#57 [feat] 사용자 주소입력, 전월세금입력 api연동
  src/components/Input.tsx
Labels: 기능구현

#58 [feat] 매물 상세정보 기능구현
  package.json
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
Labels: 기능구현

#61 [feat] 거주 형태 설정 api 연동
  src/components/Input2.tsx
Labels: 기능구현

#64 [feat] 오피스텔 api 연동
  src/components/Input2.tsx
Labels: 기능구현

#66 [feat] 주택,빌라 하위버튼들 api연동
  src/components/Input.tsx
  src/components/Input2.tsx
Labels: 기능구현

#67 [feat] 아파트 옵션 api 연동
  src/components/Input2.tsx
Labels: 기능구현

#68 [feat:] 원룸투룸 api 연동
  src/App.tsx
  src/components/Input2.tsx
  src/components/Login.tsx
  src/components/Navbar.tsx
  src/pages/MainPage.tsx
Labels: 기능구현

#73 [design] 입력칸 퍼블리싱 수정
  src/components/Input.tsx
  src/components/Login.tsx
  src/components/Signup.tsx
  src/pages/AptPage.tsx
  src/pages/HousePage.tsx
  src/pages/OfficePage.tsx
  src/pages/RoomPage.tsx
Labels: 퍼블리싱

#75 [feat] 젠킨스 파일 추가.
  Jenkinsfile
Labels: 기능구현

#79 [chore] 도커 파일 수정
  .env
  Dockerfile
  vite.config.ts
Labels: 환경설정

#80 [feat] 주소입력 바탕으로 지도 중심위치 변경
  src/App.tsx
  src/components/Input.tsx
  src/components/Map.tsx
  src/components/MapContext.tsx
Labels: 기능구현

#83 [refactor] 도커파일 1차 수정.
  Dockerfile
Labels: 리팩토링

#84 [feat] 계약서 상세 내용 연동
  .env
  src/assets/img/Checkboxes.svg
  src/components/ContractPaper.tsx
  src/pages/ContractPage.tsx
Labels: 기능구현

#87 [feat] 지도에 클러스터 마커 생성
  src/components/Map.tsx
  src/components/Sidebar.tsx
Labels: 기능구현

#90 [feat] 크롤링 api 연동 수정
  .gitignore
  package.json
  src/components/Map.tsx
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
Labels: 기능구현

#92 [refactor] 도커컴포즈 네트워크 수정
  docker-compose.yml
Labels: 리팩토링

#97 [refactor] hmr 추가완료
  package-lock.json
  package.json
  vite.config.ts
  yarn.lock
Labels: 리팩토링

#100 [refactor] vite.config.js 환경 구분 로직 추가 및 수정
  Dockerfile
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 기능구현, 리팩토링

#102 [feat] 작성된 계약서 이미지 변환
  package.json
  src/components/ContractPaper.tsx
  src/pages/ContractPage.tsx
  src/pages/StoragePage.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 기능구현

#106 [refactor] api 연동 호출 주소 수정
  src/components/ContractPaper.tsx
  src/components/Input.tsx
  src/components/Input2.tsx
  src/components/Login.tsx
  src/components/Navbar.tsx
  src/components/Navbar2.tsx
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
  src/components/Signup.tsx
  src/pages/ContractPage.tsx
  src/pages/StoragePage.tsx
  src/vite-env.d.ts
Labels: 리팩토링

#108 [test] 요청 테스트
  Jenkinsfile
  package-lock.json
  yarn.lock
Labels: 기능구현

#105 [fix] 버튼 수정 및 기타 오류 수정
  src/components/Input.tsx
  src/components/Input2.tsx
  src/components/Login.tsx
  src/components/Sidebar.tsx
  src/components/Signup.tsx
  src/pages/AptPage.tsx
  src/pages/HousePage.tsx
  src/pages/OfficePage.tsx
  src/pages/RoomPage.tsx
  tsconfig.json
Labels: 오류수정

#110 [design] Input 페이지 퍼블리싱 수정
  index.html
  public/houseadvisor.png
  public/vite.svg
  src/components/Input.tsx
  src/components/Input2.tsx
  src/components/Map.tsx
Labels: 퍼블리싱

#112 [feat] 작성된 계약서 list 연동
  src/pages/ContractPage.tsx
  src/pages/StoragePage.tsx
Labels: 기능구현

#113 [feat] 지도 중심위치 설정 및 마커 구현
  src/components/Input.tsx
  src/components/Map.tsx
  src/components/MapContext.tsx
  src/components/MapMarker.tsx
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
  src/pages/AptPage.tsx
  yarn.lock
Labels: 기능구현

#115 [design] 사이드바 퍼블리싱 수정
  package.json
  src/components/Input.tsx
  src/components/Map.tsx
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
  src/pages/AptPage.tsx
  yarn.lock
Labels: 퍼블리싱

#118 [design] 사이드바 퍼블리싱 수정
  src/components/Input.tsx
  src/components/Map.tsx
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
  src/pages/AptPage.tsx
  src/pages/HousePage.tsx
  src/pages/OfficePage.tsx
  src/pages/RoomPage.tsx
Labels: 퍼블리싱

#120 [feat] 보관함 페이지 리스트 연동
  src/assets/img/UploadIcon.svg
  src/components/ContractPaper.tsx
  src/components/Login.tsx
  src/pages/ContractPage.tsx
  src/pages/StoragePage.tsx
Labels: 기능구현

#122 [design] 상담페이지 퍼블리싱 수정
  src/App.tsx
  src/assets/img/AirplaneBtn.svg
  src/assets/img/Arrow.svg
  src/assets/img/Avatar.svg
  src/assets/img/Questions.svg
  src/components/Navbar.tsx
  src/components/Sidebar.tsx
  src/components/Sidebar2.tsx
  src/pages/ConsultingPage.tsx
  src/pages/ContractPage.tsx
  src/pages/DepositConsultingPage.tsx
  src/pages/MonthlyConsultingPage.tsx
Labels: 퍼블리싱

#124 [design] 메인페이지, 상단바 수정
  src/assets/img/Main.svg
  src/components/Navbar.tsx
  src/components/Navbar2.tsx
  src/pages/MainPage.tsx
Labels: 퍼블리싱

#125 [design] 계약서 페이지, 보관함 페이지 퍼블리싱 수정
  src/assets/img/Checkboxes.svg
  src/components/ContractPaper.tsx
  src/index.css
  src/pages/ContractPage.tsx
  src/pages/StoragePage.tsx
Labels: 기능구현, 퍼블리싱

#126 [feat] 상담페이지 api 연동
  src/pages/DepositConsultingPage.tsx
Labels: 기능구현

#129 [design] 메인페이지 버튼, 사이드바 수정
  src/assets/img/SearchBtnBottom.svg
  src/assets/img/SearchBtnTop.svg
  src/components/Sidebar.tsx
  src/pages/MainPage.tsx
Labels: 퍼블리싱

#131 [feat] 웹소켓 연동
  src/pages/DepositConsultingPage.tsx
Labels: 기능구현, 리팩토링

#133 [fix] chat api 연동 수정
  src/pages/DepositConsultingPage.tsx
Labels: 오류수정

#135 [refactor] 전체적인 리펙토링
  src/components/Input.tsx
  src/components/Input2.tsx
  src/components/Login.tsx
  src/components/Sidebar.tsx
  src/pages/ContractPage.tsx
  src/pages/DepositConsultingPage.tsx
Labels: 리팩토링

#138 [feat] 계약서 페이지 매물 정보
  src/components/Sidebar2.tsx
  src/pages/ContractPage.tsx
Labels: 기능구현, 리팩토링

#139 [fix] 상담페이지 오류 수정
  package.json
  src/pages/DepositConsultingPage.tsx
  src/pages/MonthlyConsultingPage.tsx
  yarn.lock
Labels: 오류수정

#141 [design] 상담페이지 반응형 구현
  src/pages/DepositConsultingPage.tsx
  src/pages/MonthlyConsultingPage.tsx
Labels: 퍼블리싱

#142 [fix] 상담페이지 말풍선 수정
  src/pages/DepositConsultingPage.tsx
  src/pages/MonthlyConsultingPage.tsx
Labels: 오류수정

#145 [refactor] 웹소켓 프록시 설정
  vite.config.ts
Labels: 기능구현, 리팩토링

#147 [refactor] vite.config.js 타겟:wss로 변경
  vite.config.ts
Labels: 리팩토링

#149 [refactor] vite.config.js 수정
  vite.config.ts
Labels: 기능구현, 리팩토링
